### ISSUE TITLE
getting error message even if I am logged in

### ISSUE THREAD

**Issue by baditaflorin** [gragland/chatgpt-chrome-extension#1]
Error. Make sure you're running the server by following the instructions on https://github.com/gragland/chatgpt-everywhere. Also make sure you don't have an adblocker preventing requests to localhost:3000.

In the terminal I still see 

Please sign in to ChatGPT using the Chromium browser window and dismiss the welcome modal...
Please sign in to ChatGPT using the Chromium browser window and dismiss the welcome modal...
Please sign in to ChatGPT using the Chromium browser window and dismiss the welcome modal...

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/2330999/206054433-39982318-cb71-4a7d-ba94-6e9aa763dd08.png">

system used: 
Macosx

**Comment by gragland** [comment]
This weekend I’ll get it updated to the latest version of this library we’re using, so auth no longer uses chromium: https://github.com/transitive-bullshit/chatgpt-api

That should fix the issue. Happy to accept a pull request if anyone wants to tackle it sooner though.

**Comment by gragland** [comment]
I just updated the server code to longer require signing in via Chromium. Grab the latest version of this repo and following the new setup instructions to add your ChatGPT Session token. Hopefully that fixes this issue!
