### ISSUE TITLE
Error: ChatGPTAPI error 429, Too Many Requests

### ISSUE THREAD

**Issue by cmoleka** [gragland/chatgpt-chrome-extension#12]
There appears to be an issue with the second step of the sever initialization.

```
 const error = new ChatGPTError(msg);
 ChatGPTError: ChatGPTAPI error 429
 statusCode: 429,
 statusText: 'Too Many Requests'
```

Although I tried implementing a solution found here: [Error: ChatGPTAPI error 429](https://github.com/transitive-bullshit/chatgpt-api/issues/111), it doesn't seem to fix the issue. Anyone else ran into this?

I also think it's worth mentioning that this error start appearing within the past few days from what I have gathered.

**Comment by cmoleka** [comment]
The issue has been fixed by disabling Image plugin from config.js

Not entirely sure why it was causing an error, however for my use-case Image is not required.

**Comment by gragland** [comment]
This may be related to OpenAI's bot protection. We need to upgrade to the latest version of chatgpt-api: https://github.com/gragland/chatgpt-chrome-extension/issues/13

Will do this when I have time, but pretty busy. If anyone wants to tackle it feel free!

**Comment by gragland** [comment]
Just updated the extension. Get the latest version, re-run `npm run install`, and then try again.

Keep in mind ChatGPT is pretty overloaded right now. You can try their website directly to see if it's an issue with the extension or their site just isn't working.
