### ISSUE TITLE
getOpenAIAuth-Having issues getting my session ID

### ISSUE THREAD

**Issue by y0himba** [gragland/chatgpt-chrome-extension#18]
Hello.  I am quite new to this, and an old fart.  I am trying to follow the instructions for aquiring my session id from Chatgpt, but I simply am getting lost.

I am on Windows 10, and succesfully installed the puppeteer, just stuck on how exaclty to use it to get my session id?

Any help is appreciated.

**Comment by gragland** [comment]
Just updated the extension to utilize your email/password instead. Please update your project, re-run `npm run install`, and see the updated readme.

**Comment by y0himba** [comment]
Thank you! (still curious though)
