### ISSUE TITLE
Create .env on Mac Ventura 13.0

### ISSUE THREAD

**Issue by Chazay** [gragland/chatgpt-chrome-extension#23]
Hello, I am looking for a little help when creating the .env file. I did all the correct installs with `npm` yet I did not get a .env-example file in the install. And MacOS is not allowing me to create a .env file using TextEdit and the markdown(?) information provided in here: https://github.com/gragland/chatgpt-chrome-extension/blob/main/.env.example

I am not really great at coding-related things and would like some help in the right direction. Thanks!

**Comment by ahayat2806** [comment]
Having the same issue here;
Apparently folders beginning with a '.' on Mac are illegal as they are reserved for system files.
<img width="667" alt="image" src="https://user-images.githubusercontent.com/55039025/215158798-3153a282-463e-4571-8c70-49b2663156e9.png">
Perhaps I can edit the path declared in 'server.js'? I'll let you know if it works.

**Comment by theHowda** [comment]
I would also appreciate a help on that

**Comment by taktikz** [comment]
In Finder, show hidden files; in this case, simply the .env file with the requested/updated info.

**Comment by maurop123** [comment]
Maybe try renaming ".env.example" as something other than a dotfile (e.g. "env.example"), edit it, and then rename it back

**Comment by gragland** [comment]
I would recommend using a code editor, such as [VS code](https://code.visualstudio.com/), that shows all the files in a directory including those that are hidden.
