### ISSUE TITLE
ChatGPT Login problem

### ISSUE THREAD

**Issue by farooqbutt** [gragland/chatgpt-chrome-extension#26]
Hello,
I would like to use this extension, however, I am unable to log in to my **ChatGPT** account using a password as I have set it up with Google Authentication. Could you please advise on what password I should set in the **.env** file? I have tried using my Google password, but it resulted in a failed authentication process and the headless browser was closed.
Thank you,
Farooq.

**Comment by mysticalherbz** [comment]
same problem

**Comment by enok** [comment]
here also

**Comment by sharma14skss** [comment]
In server.js add isGoogleLogin : true in line number 15, it will try to login with google account.

`const gptApi = new ChatGPTAPIBrowser({
  email: process.env.OPENAI_EMAIL,
  password: process.env.OPENAI_PASSWORD,
  **isGoogleLogin: true**
});`

**Comment by maurop123** [comment]
https://github.com/gragland/chatgpt-chrome-extension/pull/27 will fix this issue

**Comment by kvisalini** [comment]
@sharma14skss I tried what you suggested. But, the Google Auth asked me to verify a code on my phone, but the login crashed on my browser quoting 

`throw new ChatGPTError("Failed to authenticate session");`

Is there any kinda workaround?

**Comment by gragland** [comment]
Should be fixed now that I merged #27
