### ISSUE TITLE
Error: ChatGPT failed to refresh auth token. TypeError: fetch failed

### ISSUE THREAD

**Issue by MWorld2021** [gragland/chatgpt-chrome-extension#4]
Can you provide the method of proxy when requesting ChatGPT ？ Or Access Token Authentication/Email and password authentication mode ...

**Comment by gragland** [comment]
This is currently an open issue with the chatgpt-api library we use: https://github.com/transitive-bullshit/chatgpt-api/issues/18

For the time being you would need to manually get an updated session and add it to `.env`. Let me know if you have any ideas on how to improve this.

**Comment by rico0610** [comment]
Getting this error after adding the session token.

Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

**Comment by gragland** [comment]
Just updated the extension to use email/password instead. Get the latest version, re-run `npm run install`, and then see the updated readme.

Keep in mind ChatGPT is pretty overloaded right now. You can try their website directly to see if it's an issue with the extension or their site just isn't working.
