### ISSUE TITLE
replace url in an alert

### ISSUE THREAD

**Issue by deadcoder0904** [gragland/chatgpt-chrome-extension#5]
https://github.com/gragland/chatgpt-everywhere can be replaced with https://github.com/gragland/chatgpt-chrome-extension as i thought there is another repo while reading the code: 

https://github.com/gragland/chatgpt-chrome-extension/blob/b1edc8659758aa582e5154de873a992e5d4104df/extension/content.js#L91

**Comment by gragland** [comment]
Ah yes forgot to change that when I renamed the repo. Fixed!
